#!/bin/bash
echo mcmpget
wget -nv -c -O https://raw.githubusercontent.com/bittermc/modpack/main/modslist.txt && echo Updated mods list.


cat modslist.txt | while read line; do
	if [[ "`echo $line | awk '{print $1}'`" == "$1" ]]; then
		if [[ -n "$line" ]]; then
			# echo $line | awk '{print $3}' | xargs wget -nv -c -O "`echo $line | awk '{print $2}'`.jar"
			aria2c -c -o "$(echo $line | awk '{print $2}').jar" "$(echo $line | awk '{print $3}')" & disown
		else
			echo Empty line. skipping
		fi
	fi
done
